declare module "*.module.css";
declare module "intersection-observer";
declare module "react-toastify";
declare module "react-router-dom";
declare module "loadable-image";
declare module "timeago.js";
declare module "path-browserify";
declare module "react-lazy-load-image-component"
declare module "react-responsive-masonry"
